#! /bin/bash

numlines () {   
if [[ $(cat $1 | wc -l)  -gt 10 ]]
then
    echo  the file has more than 10 lines
fi
if [[ $(cat $1 | wc -l)  -le 10  &&  $(cat $1 | wc -l) -ne 0 ]]
then
    echo  the file has less than or equal 10 lines
fi
if [[ $(cat $1 | wc -l)  -eq 0 ]]
then
    echo  the file is empty
fi
}
numlines sample.csv

